version: '3.7'
services:
  smarthome:
    container_name: server
    hostname: smarthome
    build: ./
    restart: always
    environment:
      - PORT=3000
    ports:
      - "${PORT:-3000}:${PORT:-3000}"